FROM ruby:3.4.1-slim

RUN apt-get update && apt-get install -y zip && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
RUN zip -r campfire.zip . -x ".git/*" -x "tmp/*" -x "log/*" -x "storage/*"

CMD ["cat", "/app/campfire.zip"]
